### ISSUE TITLE
Markdown 与 Latex 语法冲突

### ISSUE THREAD

**Issue by JasinYip** [mycolorway/simditor-markdown#5]
我们自己有一个 Latex 渲染模块，可以对字符串中使用 `$` 包围的 Latex 公式进行渲染。比如：

行内（两个 `$` 包围）

```
$a_0+a_1+a_2+a_3$
```

行间（四个 `$` 包围）

```
$$a_0+a_1+a_2+a_3$$
```

里面的 `_` 会被识别为 Markdown 的特殊称号，于是 `0+a` 和 `2+a` 就被识别成斜体了。

请问有没有什么方法，可以让 Simditor-Markdown 不识别 `$` 或 `$$` 的内容？

**Comment by farthinker** [comment]
simditor-markdown使用的这两个开源库实现html和markdown之间的转换，你可以看看他们的文档，有没有办法自定义转换规则：

https://github.com/domchristie/to-markdown
https://github.com/chjj/marked
